### ISSUE TITLE
Перевод: турфы

### ISSUE THREAD

**Issue by AndyAdjutor** [AndyAdjutor/SovietBay#27]
turf
airless floor(безвоздушный пол?)
light floor
reinforced floor(укреплённый пол?)
engraved floor(гравированный пол?)
vacuum floor
plating(обшивка вроде)
airless plating
iron sand(железистый песчаник
brig floor
skipjack floor
grass patch(травяной покров?)
command(в значении турфа)
A huge chunk of metal used to seperate rooms
You replace the light bulb
The lightbulb seems fine, no need to replace it
You remove the broken plating
You forcefully pry off the planks, destroying them in the process
You remove the [I.name]
You unscrew the planks
You need more rods
Reinforcing the floor...
You must remove the plating first
This section is too damaged to support a tile. Use a welder to fix the damage
You shovel the grass
You cannot shovel this
You fix some dents on the broken plating
You need more welding fuel to complete this task
про стены
It looks fully intact
It looks slightly damaged
It looks moderately damaged
It looks heavily damaged
There is fungus growing on [src]
The [src] spontaneously combusts!(про термит)
The thermite starts melting through the wall
Constructing support lattice ...
The plating is going to need some support
Something you are carrying is preventing you from leaving. Don't play stupid; you know exactly what it is(когда пытаешься свалить на другой уровень с диском от нюки)

**Comment by Bradley-Blya** [comment]
турф
Тут я не думаю, что название должно отличатся от воздушного пола.
пол с подсветкой/полы с подсветкой
упрочненный/армированный пол
гравированный пол
Эти полы встречаются в камерах с газами в атмосферке, пускай называются упрочненными.
обшивка
обшивка
железистые пески/железистый песок
Как я понимаю, это полы с шаттла. Не думаю, что есть смысл выдавать им особенные названия.
@
травяной покров
Какой еще команд?
Огромная металлическая конструкция, формирующая переборки. 
Ты поменял лампочку./Вы заменили лампу.
Лампочка работает исправно, заменять ее не нужно.
Ты убрал разбитую плитку./Вы убираете разбитую плитку.
Ты с усилием отодрал паркет и он сломался/развалился./Вы с усилием отдираете паркет, и он ломается/разваливается на части.
Ты снял/убрал. / Вы снимаете/убираете. (ВЫ убрали плитку, вродь норм, но и остльные варианты норм)
Ты открутил паркет./Вы откручиваете паркет.
Вам нужно больше арматуры/арматурин/стержней/железных палок.
Вы упрочняете пол арматурой.
Сначала нужно убрать обшивку.
Эта часть обшивки слишком повреждена. Отремонтируйте ее горелкой.
Вы выкапываете/выкорчевываете траву.
Вы не можете это выкопать.
Вы устранили повреждения обшивки.
Вам понадобится больше топлива для горелки.
про стены
Выглядит абсолютно целой.
Выглядит немного поврежденной.
Выглядит изрядно поврежденной.
Выглядит очень поврежденной.
[src] покрыт грибком.
[src] внезапно загорается.
Термит прожигает стену насквозь.
Вы сооружаете структурную решетку.
Обшивке нужен каркас.
хз

**Comment by Wyderar** [comment]
Последнее: Что-то, что Вы несете, мешает Вам улететь дальше. Вы прекрасно знаете, что это, не притворяйтесь

**Comment by Bradley-Blya** [comment]
Я надеюсь, теперь ясно, почему я не стал это переводить? Даже такой вариант красивее:
"Вы несете что-то, с чем нельзя улететь. Не придуривайтесь, вы прекрасно знаете, что это.

**Comment by Wyderar** [comment]
Да, так будет короче

**Comment by Bradley-Blya** [comment]
Ну да, короче. Но главное - так можно избежать этого:  https://www.youtube.com/watch?v=XCkqvyzchJ8
