### ISSUE TITLE
Перевод: оружие дальнего боя

### ISSUE THREAD

**Issue by AndyAdjutor** [AndyAdjutor/SovietBay#30]
Пока переношу пушки буду копировать сюда нужный текст.

**Comment by AndyAdjutor** [comment]
/obj/item/weapon/gun:
gun
Its a gun. It's pretty terrible, though.
"struck", "hit", "bashed" - при желании можно ещё добавить слов, как для русского, так и для английского
Your fingers are much too large for the trigger guard!
[user] shoots \himself in the foot with \the [src]
You shoot yourself in the foot with \the [src]!
You refrain from firing your [src] as your intent is set to help.
[src] is not ready to fire again!
\The [user] fires \the [src] by reflex!
You fire \the [src] by reflex!
\The [user] fires \the [src]!
You fire \the [src]!
[user] sticks their gun in their mouth, ready to pull the trigger...
[user] decided life was worth living
[user] pulls the trigger.
You feel rather silly, trying to commit suicide with a toy.
Point blank shot in the mouth with \a [in_chamber]
Ow...(суицид оружием с голоуроном)
The fire selector is set to [current_mode.name].
\The [src] is now set to [new_mode.name].

**Comment by AndyAdjutor** [comment]
/obj/item/weapon/gun/projectile:
A gun that fires bullets.
[src] already has a magazine loaded.
[user] inserts [AM] into [src]
You insert [AM] into [src].
[src] is full!
[user] reloads [src].
You load [count] round\s into [src].
[user] removes [ammo_magazine] from [src].
You remove [ammo_magazine] from [src].</span>
[user] unloads [src].
You unload [count] round\s from [src].
[src] is empty.
[ammo_magazine] falls out and clatters on the floor!
It has \a [ammo_magazine] loaded.
Has [getAmmo()] round\s remaining.

**Comment by Wyderar** [comment]
/obj/item/weapon/gun:
gun
Это оружие. Думаю, оно довольно ужасно.
Хер знает, надо тестить использование
Ваши пальцы слишком велики, чтобы нормально стрелять!
[user] стреляет \себе в ногу из \[src]
Вы стреляете себе в ногу из \[src]!
Вы удерживаете себя от выстрела из [src] из-за мирных намерений. //???
[src] ещё не готов стрелять!
\[user] рефлекторно стреляет из \[src]!
Вы рефлекторно стреляет из \[src]!
\[user] стреляет из \[src]!
Вы стреляете из \[src]!
[user] засовывает ствол оружия себе в рот, уже готовый нажать курок...
[user] решает, что жизнь стоит того, чтобы жить. // дичь
[user] спускает курок.
Вы чувствуете себя умственно неполноценным, когда понимаете, что пытались застрелиться игрушкой //дичь
Выстрел вплотную в рот в \[in_chamber] //дичь; это кусок админ лога?
Эмм...(суицид оружием с голоуроном)
Селектор режима огня переключен в режим [current_mode.name].
\[src] переключен в режим [new_mode.name].

**Comment by Wyderar** [comment]
obj/item/weapon/gun/projectile:
Оружие, стреляющее пулями.
В [src] уже вставлен магазин.
[user] вставляет [AM] в [src]
Вы вставляете [AM] в [src].
[src] полон!
[user] перезаряжает [src].
Вы заряжаете [count] патрон\ов в [src].
[user] отсоединяет [ammo_magazine] от [src]. //дичь
Вы отсоединяете [ammотmagazin] от [src]. //дичь
[user] разряжает [src].
Вы разряжаете [count] патрон\ов из [src].
[src] пуст.
[ammo_magazine] падает и ударяется об пол!
It has \a [ammo_magazine] loaded. Без понятия
Остался\ось [getAmmo()] патрон\ов.
