### ISSUE TITLE
[Фичи рас] Кулеры для СПУ.

### ISSUE THREAD

**Issue by KostegSS13** [AndyAdjutor/SovietBay#54]
Предлагаю вернуть СПУ кулер который будет потреблять их энергию но взамен будет защищать от космоса/не давать так сильно в нем перегреваться. Либо дать СПУ другую возможность выживать в космосе, такую как работающие на них баллоны с кислородом либо что-то еще.

**Comment by AndyAdjutor** [comment]
https://github.com/AndyAdjutor/SovietBay/commit/ad684d7794a22b4e9c798174fd5b9bb792af2d44
